[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "E4KC2A8JJPK6GRiXEPhL64p8KvKke7BPdejD72noPkjP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
